development:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: password

test: &test
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 3306
      username: root
      password: password

production:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: password
cucumber:
  <<: *test
